name: C++ CI

on:
  push:
    branches: [ "main", "master" ]
    paths:
      - 'cpp/**'
  pull_request:
    branches: [ "main", "master" ]
    paths:
      - 'cpp/**'

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: brew install cmake libtorrent-rasterbar

    - name: Configure CMake
      run: cmake -B cpp/build -S cpp

    - name: Build
      run: cmake --build cpp/build -j4

    - name: Test
      working-directory: cpp/build
      run: mkdir -p /tmp/test_home && HOME=/tmp/test_home ctest --output-on-failure
